site_name: CIV Programming - Robotics
site_description: ICTPRG430 & ICTPRG439 - Object-Oriented Programming and Component Reuse
site_author: Your Institution
site_url: https://yoursite.com/robotics-course

# Repository info (optional - for GitHub integration)
repo_name: robotics-programming-course
repo_url: https://github.com/yourusername/robotics-course
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Your Institution

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    # Light mode
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Plugins
plugins:
  - search:
      lang: en
  - glightbox:  # Image lightbox
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
      timezone: Australia/Perth

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mermaid2
  - video
  - toc:
      permalink: true
      title: On this page
      toc_depth: 2
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation structure
nav:
  - Home: index.md
  - Learning & Assessment Plan: revised-lap.md
  - Week 1 - Unit Testing & Binary Search:
    - Session 1: sessions/session-01.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 2 - Advanced Testing & Algorithms:
    - Session 2: sessions/session-02.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 3 - Professional Testing Environment:
    - Session 3: sessions/session-03.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 4 - Object Model & Class Fundamentals:
    - Session 4: sessions/session-04.md
    - Theory Session: 'sessions/session-04/#1-why-object-oriented-programming-for-robotics'
    - Hands-on Exercise: 'sessions/session-04/#hands-on-exercise-mock-ir-sensor-class'
    - Live Demonstration: 'sessions/session-04/#live-demonstration-lidar-implementation-across-programming-paradigms'
    - Extension Activity: 'sessions/session-04/#extension-activity-advanced-lidar-data-filtering'
    - Lab Setup: 'sessions/session-04/#lab-1-webots-robot-simulator-setup'
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 5 - Advanced Class Features:
    - Session 5: sessions/session-05.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 6 - Inheritance & Polymorphism:
    - Session 6: sessions/session-06.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 7 - File I/O & Documentation:
    - Session 7: sessions/session-07.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 8 - Felipe Lab 1 OOP Refactoring:
    - Session 8: sessions/session-08.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 9 - Felipe Lab 2 OOP Implementation:
    - Session 9: sessions/session-09.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 10 - Felipe Lab 3 OOP Navigation:
    - Session 10: sessions/session-10.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 11 - Felipe Lab 4 OOP Control Systems:
    - Session 11: sessions/session-11.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 12 - Felipe Lab 5 OOP Mission Integration:
    - Session 12: sessions/session-12.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 13 - ROS Component Analysis:
    - Session 13: sessions/session-13.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 14 - Component Evaluation:
    - Session 14: sessions/session-14.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 15 - Integration Planning:
    - Session 15: sessions/session-15.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 16 - ROS Component Integration:
    - Session 16: sessions/session-16.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 17 - System Assembly & Documentation:
    - Session 17: sessions/session-17.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Week 18 - Portfolio Review:
    - Session 18: sessions/session-18.md
    - Resources: downloads.md
    - Assessment: assessment.md
  - Reference:
    - Glossary: glossary.md

# Extra CSS and JS
extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Footer social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
  version:
    provider: mike
