site_name: CIV Programming - Robotics
site_description: ICTPRG430 & ICTPRG439 - Object-Oriented Programming and Component Reuse
site_author: Your Institution
site_url: https://yoursite.com/robotics-course

# Repository info (optional - for GitHub integration)
repo_name: robotics-programming-course
repo_url: https://github.com/yourusername/robotics-course
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Your Institution

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.integrate  # This moves TOC to left sidebar
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    # Light mode
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Plugins
plugins:
  - search:
      lang: en

  - mkdocs-video:


  - glightbox:  # Image lightbox
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
      timezone: Australia/Perth
  - iframe:

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 2
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation structure - Simplified and clean
nav:
  - Home: index.md
  - Course Overview: course-overview/revised_lap.md
  - Unit Testing (Weeks 1-3):
    - Week 1 - Unit Testing & Binary Search: sessions/session-01.md
    - Week 2 - Advanced Testing & Algorithms: sessions/session-02.md
    - Week 3 - Professional Testing Environment: sessions/session-03.md
  - Object-Oriented Programming (Weeks 4-12):
    - Week 4 - Object Model & Class Fundamentals: sessions/session-04.md
    - Week 5 - Advanced Class Features: sessions/session-05.md
    - Week 6 - Inheritance & Polymorphism: sessions/session-06.md
    - Week 7 - File I/O & Documentation: sessions/session-07.md
    - Week 8 - Lab 1 OOP Refactoring: sessions/session-08.md
    - Week 9 - Lab 2 OOP Implementation: sessions/session-09.md
    - Week 10 - Lab 3 OOP Navigation: sessions/session-10.md
    - Week 11 - Lab 4 OOP Control Systems: sessions/session-11.md
    - Week 12 - Lab 5 OOP Mission Integration: sessions/session-12.md
  - Labs 1 -4: Robotics-Simulation-Labs-main/Lab3/ReadMe.md
      
  - ROS (Weeks 13-18):
    - Week 13 - Component Analysis: sessions/session-13.md
    - Week 14 - Component Evaluation: sessions/session-14.md
    - Week 15 - Integration Planning: sessions/session-15.md
    - Week 16 - Component Integration: sessions/session-16.md
    - Week 17 - System Assembly & Documentation: sessions/session-17.md
    - Week 18 - Portfolio Review: sessions/session-18.md
  - Resources:
    - Downloads: downloads.md
    - Assessment: assessment.md
  - Reference:
    - Glossary: glossary.md


# Extra CSS and JS
# extra_css:
#   - stylesheets/custom.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

# Footer social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername

